#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <limits>
#include <tuple>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;


class BlackjackWinner {
public:
	int winnings(int bet, int dealer, int dealerBlackjack, int player, int blackjack) {
	    if(dealerBlackjack or blackjack){
		if(dealerBlackjack==blackjack) return 0;
		else return bet * ((dealerBlackjack < blackjack)? 1.5 : -1);
	    }
	    if(21 < dealer && 21 < player) return -bet;
	    if( (dealer < player || 21 < dealer) && player <= 21) return bet;
	    return (dealer == player)? 0 : -bet;
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit-pf 2.3.0
#include <iostream>
#include <string>
#include <vector>
#include <ctime>
#include <cmath>
using namespace std;
bool KawigiEdit_RunTest(int testNum, int p0, int p1, int p2, int p3, int p4, bool hasAnswer, int p5) {
	cout << "Test " << testNum << ": [" << p0 << "," << p1 << "," << p2 << "," << p3 << "," << p4;
	cout << "]" << endl;
	BlackjackWinner *obj;
	int answer;
	obj = new BlackjackWinner();
	clock_t startTime = clock();
	answer = obj->winnings(p0, p1, p2, p3, p4);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		res = answer == p5;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
		if (hasAnswer) {
			cout << "Desired answer:" << endl;
			cout << "\t" << p5 << endl;
		}
		cout << "Your answer:" << endl;
		cout << "\t" << answer << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	bool disabled;
	bool tests_disabled;
	all_right = true;
	tests_disabled = false;
	
	int p0;
	int p1;
	int p2;
	int p3;
	int p4;
	int p5;
	
	// ----- test 0 -----
	disabled = false;
	p0 = 4;
	p1 = 18;
	p2 = 0;
	p3 = 18;
	p4 = 0;
	p5 = 0;
	all_right = (disabled || KawigiEdit_RunTest(0, p0, p1, p2, p3, p4, true, p5) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 1 -----
	disabled = false;
	p0 = 26;
	p1 = 21;
	p2 = 1;
	p3 = 21;
	p4 = 0;
	p5 = -26;
	all_right = (disabled || KawigiEdit_RunTest(1, p0, p1, p2, p3, p4, true, p5) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 2 -----
	disabled = false;
	p0 = 100;
	p1 = 25;
	p2 = 0;
	p3 = 21;
	p4 = 1;
	p5 = 150;
	all_right = (disabled || KawigiEdit_RunTest(2, p0, p1, p2, p3, p4, true, p5) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 3 -----
	disabled = false;
	p0 = 78;
	p1 = 22;
	p2 = 0;
	p3 = 23;
	p4 = 0;
	p5 = -78;
	all_right = (disabled || KawigiEdit_RunTest(3, p0, p1, p2, p3, p4, true, p5) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	if (all_right) {
		if (tests_disabled) {
			cout << "You're a stud (but some test cases were disabled)!" << endl;
		} else {
			cout << "You're a stud (at least on given cases)!" << endl;
		}
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// In the game of blackjack, if the player scores higher than the dealer or the dealer goes over 21, and the player does not go over 21, then he wins his bet (in addition to keeping his original wager).  If he scores 21 or less, and the same as the dealer, the hand is a push, and he keeps his bet.  Otherwise, if he scores lower than the dealer, or goes over 21 (regardless of whether or not the dealer also does so), then he loses his bet.
// 
// A "blackjack" is a special kind of 21 point hand that beats all other hands.  In such a case, the player wins 1.5 times his original bet.  If both dealer and player have a blackjack, then the hand is a push.  Note that if the dealer has a blackjack, and the player has a 21 (but does not have blackjack), then the dealer wins, and the player loses his wager.
// 
// You are given an int bet indicating the players wager, an int dealer indicating the dealer's score, and an int player indicating the player's score.  Finally, you are given an int blackjack, which will be equal to 1 if the player has a blackjack, or 0 otherwise.  Likewise, you are given the int dealerBlackjack.
// 
// You are to return the amount of money the player wins or loses on the hand.  A win should return a positive number, either the player's bet, or 1.5 times his bet.  A loss should be returned as a negative number.  A push should return 0.
// 
// 
// 
// 
// DEFINITION
// Class:BlackjackWinner
// Method:winnings
// Parameters:int, int, int, int, int
// Returns:int
// Method signature:int winnings(int bet, int dealer, int dealerBlackjack, int player, int blackjack)
// 
// 
// CONSTRAINTS
// -bet will be between 2 and 100, inclusive, and will be even.
// -dealer will be between 17 and 26, inclusive.
// -dealerBlackjack will be 0 or 1.
// -dealerBlackjack may only be 1 if dealer is 21.
// -player will be between 4 and 30, inclusive.
// -blackjack will be 0 or 1.
// -blackjack may only be 1 if player is 21.
// 
// 
// EXAMPLES
// 
// 0)
// 10
// 20
// 0
// 21
// 0
// 
// Returns: 10
// 
// Here, the player beats the dealer (without blackjack), and wins his bet.
// 
// 1)
// 26
// 21
// 1
// 21
// 0
// 
// Returns: -26
// 
// Here, the player loses... even though both dealer and player have 21, the dealer has a blackjack.
// 
// 2)
// 100
// 25
// 0
// 21
// 1
// 
// Returns: 150
// 
// Here, the dealer went over, so as long as the player didn't go over, he's a winner.  In fact, since he has a blackjack, he wins 1.5 times his original bet.
// 
// 3)
// 78
// 22
// 0
// 23
// 0
// 
// Returns: -78
// 
// Even though the dealer went over, so did the player, so the player loses.
// 
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit-pf 2.3.0!
