#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <limits>
#include <tuple>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;

int search(vector<int> people, int left, int right, int time){
// 行きと帰りをまとめて一回のsearchで処理する
    int now = 1<<29, size=people.size();
    // どの二人を渡すかは二重forループのiとjで選ぶ
    for(int i=0; i<size; ++i){
	for(int j=i+1; j<size; ++j){

	    // 行きの部分
	    // leftのi,j番目のbitが1であるかどうかの判断（両方共1じゃないとダメ） 
	    if( ~(left>>i)%2 || ~(left>>j)%2 ) continue;
	    int go = max(people[i], people[j]);
	    int cross = (1<<i) + (1<<j);
	    int new_left = left - cross, new_right = right + cross;
	    if(new_left<=0) return go+time;

	    // 帰りの部分
	    int back = 1<<29, who=0;
	    for(int k=0; k<size; ++k){
		// 行きで渡った後後の右側（new_righ)の中で一番速い人を探す
		if( (new_right>>k)%2 && people[k]<back ){
		    back = people[k];
		    who = k;
		}
	    }
	    cross = 1 << who;
	    new_left += cross; new_right -= cross;
	    now = min(now, search(people, new_left, new_right, time+go+back));
	}
    }
    return now;
}

class BridgeCrossing {
public:
	int minTime(vector <int> times) {
	    int size=times.size();
	    // 人数分だけ1を詰める処理
      	    int left=(1<<size)-1, right=0;
	    if(size==1) return times[0];

	    return search(times, left, right, 0);
	}
};

//          debug用(bitset<bit数>を使うと簡単に2進数表現できる)
//	    cout << "first left is "<< bitset<7>(left) << endl;

// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit-pf 2.3.0
#include <iostream>
#include <string>
#include <vector>
#include <ctime>
#include <cmath>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <int> p0, bool hasAnswer, int p1) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << p0[i];
	}
	cout << "}";
	cout << "]" << endl;
	BridgeCrossing *obj;
	int answer;
	obj = new BridgeCrossing();
	clock_t startTime = clock();
	answer = obj->minTime(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		res = answer == p1;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
		if (hasAnswer) {
			cout << "Desired answer:" << endl;
			cout << "\t" << p1 << endl;
		}
		cout << "Your answer:" << endl;
		cout << "\t" << answer << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	bool disabled;
	bool tests_disabled;
	all_right = true;
	tests_disabled = false;
	
	vector <int> p0;
	int p1;
	
	// ----- test 0 -----
	disabled = false;
	p0 = {1,2,5,10};
	p1 = 17;
	all_right = (disabled || KawigiEdit_RunTest(0, p0, true, p1) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 1 -----
	disabled = false;
	p0 = {11, 2, 8, 50, 2, 100};
	p1 = 125;
	all_right = (disabled || KawigiEdit_RunTest(1, p0, true, p1) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 2 -----
	disabled = false;
	p0 = {100};
	p1 = 100;
	all_right = (disabled || KawigiEdit_RunTest(2, p0, true, p1) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 3 -----
	disabled = false;
	p0 = {100, 100, 100, 100, 100, 100};
	p1 = 900;
	all_right = (disabled || KawigiEdit_RunTest(3, p0, true, p1) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	if (all_right) {
		if (tests_disabled) {
			cout << "You're a stud (but some test cases were disabled)!" << endl;
		} else {
			cout << "You're a stud (at least on given cases)!" << endl;
		}
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// A well-known riddle goes like this: Four people are crossing an old bridge. The bridge cannot hold more than two people at once. It is dark, so they can't walk without a flashlight, and they only have one flashlight! Furthermore, the time needed to cross the bridge varies among the people in the group. For instance, let's say that the people take 1, 2, 5 and 10 minutes to cross the bridge. When people walk together, they always walk at the speed of the slowest person. It is impossible to toss the flashlight across the bridge, so one person always has to go back with the flashlight to the others. What is the minimum amount of time needed to get all the people across the bridge?
// 
// In this instance, the answer is 17. Person number 1 and 2 cross the bridge together, spending 2 minutes. Then person 1 goes back with the flashlight, spending an additional one minute. Then person 3 and 4 cross the bridge together, spending 10 minutes. Person 2 goes back with the flashlight (2 min), and person 1 and 2 cross the bridge together (2 min). This yields a total of 2+1+10+2+2 = 17 minutes spent.
// 
// You want to create a computer program to help you solve new instances of this problem. Given an vector <int> times, where the elements represent the time each person spends on a crossing, your program should return the minimum possible amount of time spent crossing the bridge.
// 
// DEFINITION
// Class:BridgeCrossing
// Method:minTime
// Parameters:vector <int>
// Returns:int
// Method signature:int minTime(vector <int> times)
// 
// 
// NOTES
// -In an optimal solution, exactly two people will be sent across the bridge with the flashlight each time (if possible), and exactly one person will be sent back with the flashlight each time.  In other words, in an optimal solution, you will never send more than one person back from the far side at a time, and you will never send less than two people across to the far side each time (when possible).
// 
// 
// CONSTRAINTS
// -times will have between 1 and 6 elements, inclusive.
// -Each element of times will be between 1 and 100, inclusive.
// 
// 
// EXAMPLES
// 
// 0)
// { 1, 2, 5, 10 }
// 
// Returns: 17
// 
// The example from the text.
// 
// 1)
// { 1, 2, 3, 4, 5 }
// 
// Returns: 16
// 
// One solution is: 1 and 2 cross together (2min), 1 goes back (1min), 4 and 5 cross together (5min), 2 goes back (2min), 1 and 3 cross together (3min), 1 goes back (1min), 1 and 2 cross together (2min). This yields a total of 2 + 1 + 5 + 2 + 3 + 1 + 2 = 16 minutes spent.
// 
// 2)
// { 100 }
// 
// Returns: 100
// 
// Only one person crosses the bridge once.
// 
// 3)
// { 1, 2, 3, 50, 99, 100 }
// 
// Returns: 162
// 
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit-pf 2.3.0!
