#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <limits>
#include <tuple>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;


class ReportAccess {
public:
	vector <string> whoCanSee(vector <string> userNames, vector <string> allowedData, vector <string> reportData) {
	    vector<string> result;
	    for(unsigned int i = 0; i < allowedData.size(); ++i){
		stringstream allow(allowedData[i]);
		string temp;
		vector<string> allows;
		while(allow >> temp)
		    allows.push_back(temp);
		bool flag = true;
		for(unsigned int j = 0; j < reportData.size(); ++j){
		    if(find(allows.begin(), allows.end(), reportData[j])==allows.end()){
			flag = false;
			break;
		    }
		}
		if(flag) result.push_back(userNames[i]);
	    }
	    sort(result.begin(), result.end());
	    return result;
	}
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit-pf 2.3.0
#include <iostream>
#include <string>
#include <vector>
#include <ctime>
#include <cmath>
using namespace std;
bool KawigiEdit_RunTest(int testNum, vector <string> p0, vector <string> p1, vector <string> p2, bool hasAnswer, vector <string> p3) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p0[i] << "\"";
	}
	cout << "}" << "," << "{";
	for (int i = 0; int(p1.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p1[i] << "\"";
	}
	cout << "}" << "," << "{";
	for (int i = 0; int(p2.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p2[i] << "\"";
	}
	cout << "}";
	cout << "]" << endl;
	ReportAccess *obj;
	vector <string> answer;
	obj = new ReportAccess();
	clock_t startTime = clock();
	answer = obj->whoCanSee(p0, p1, p2);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		if (answer.size() != p3.size()) {
			res = false;
		} else {
			for (int i = 0; int(answer.size()) > i; ++i) {
				if (answer[i] != p3[i]) {
					res = false;
				}
			}
		}
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
		if (hasAnswer) {
			cout << "Desired answer:" << endl;
			cout << "\t" << "{";
			for (int i = 0; int(p3.size()) > i; ++i) {
				if (i > 0) {
					cout << ",";
				}
				cout << "\"" << p3[i] << "\"";
			}
			cout << "}" << endl;
		}
		cout << "Your answer:" << endl;
		cout << "\t" << "{";
		for (int i = 0; int(answer.size()) > i; ++i) {
			if (i > 0) {
				cout << ",";
			}
			cout << "\"" << answer[i] << "\"";
		}
		cout << "}" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	bool disabled;
	bool tests_disabled;
	all_right = true;
	tests_disabled = false;
	
	vector <string> p0;
	vector <string> p1;
	vector <string> p2;
	vector <string> p3;
	
	// ----- test 0 -----
	disabled = false;
	p0 = {"joe","nick","ted"};
	p1 = {"clients products","products orders","clients orders"};
	p2 = {"clients","products"};
	p3 = {"joe"};
	all_right = (disabled || KawigiEdit_RunTest(0, p0, p1, p2, true, p3) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 1 -----
	disabled = false;
	p0 = {"kathy","john","dan","steve","cheryl","tony"};
	p1 = {"users data","data orders","users permissions","system users controls","default","admin users"};
	p2 = {"users"};
	p3 = {"dan","kathy","steve","tony"};
	all_right = (disabled || KawigiEdit_RunTest(1, p0, p1, p2, true, p3) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	// ----- test 2 -----
	disabled = false;
	p0 = {"jim","scott","barbara"};
	p1 = {"users order products","products shipping","tracking products orders"};
	p2 = {"admin"};
	p3 = {};
	all_right = (disabled || KawigiEdit_RunTest(2, p0, p1, p2, true, p3) ) && all_right;
	tests_disabled = tests_disabled || disabled;
	// ------------------
	
	if (all_right) {
		if (tests_disabled) {
			cout << "You're a stud (but some test cases were disabled)!" << endl;
		} else {
			cout << "You're a stud (at least on given cases)!" << endl;
		}
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// PROBLEM STATEMENT
// You are working on a large database that holds information about several different aspects of your company, such as customers, partners, prospects, employees, products, etc.  Every user in the system has access to one or more types of data.  For instance, a human resources worker might only have access to employee records, while a sales person might have access to prospects, customers, and products.
// 
// You are in charge of writing reports that summarize large volumes of this information.  However, since the reports may contain more than one type of data, you need to be determine which users should be allowed to view that report.  In this case, assume that a user has permission to view a report if and only if they have permission to view all of the types of data contained in that report.
// 
// You are given a list of usernames in vector <string> userNames.  You are given a list of what data types each user can access in vector <string> allowedData, where each element of allowedData is a space-delimited list of the permitted data types for that user.  Finally, you are given a vector <string> reportData, where each element of report indicates a type of data included in the report.
// 
// You are to return a vector <string> indicating the user names of those users who should be able to access the report.  The list should be returned in alphabetical order.
// 
// 
// 
// DEFINITION
// Class:ReportAccess
// Method:whoCanSee
// Parameters:vector <string>, vector <string>, vector <string>
// Returns:vector <string>
// Method signature:vector <string> whoCanSee(vector <string> userNames, vector <string> allowedData, vector <string> reportData)
// 
// 
// CONSTRAINTS
// -userNames will have between 1 and 50 elements, inclusive.
// -Each element of userNames will contain between 1 and 50 'a'-'z' characters, inclusive.
// -allowedData will contain the same number of elements as userNames.
// -Each element of allowedData will contain between 1 and 50 characters, inclusive.
// -Each element of allowedData will contain the characters 'a'-'z' or ' '.
// -reportData will contain between 1 and 5 elements, inclusive.
// -Each element of reportData will contain between 1 and 50 'a'-'z' characters, inclusive.
// 
// 
// EXAMPLES
// 
// 0)
// {"joe", "nick", "ted"}
// {"clients products", "products orders", "clients orders"}
// {"clients", "products"}
// 
// Returns: {"joe" }
// 
// Here, only joe has access to both required data types.
// 
// 1)
// {"kathy", "john", "dan", "steve", "cheryl", "tony"}
// {"users data", "data orders", "users permissions", "system users controls", "default", "admin users"}
// {"users"}
// 
// Returns: {"dan", "kathy", "steve", "tony" }
// 
// Here, we only need one type of permission to view the report.
// 
// 2)
// {"jim", "scott", "barbara"}
// {"users order products", "products shipping", "tracking products orders"}
// {"admin"}
// 
// Returns: { }
// 
// Everyone has a variety of permissions, but nobody has the proper permission.
// 
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit-pf 2.3.0!
